### ISSUE TITLE
Update GIN

### ISSUE THREAD

**Issue by KottV** [FigBug/Voc#1]
Hi,

I build LV2 versions of all your non-slPlugins apps (PAPU, Voc, RP2A03, SN76489, MVERB2020, SID) and found similar segfault: https://linuxmusicians.com/viewtopic.php?p=118657#p118657
While VST and standalone works fine the LV2 ttl exporter crashes during generating ttl files.
The fix is simple update gin submodule to the https://github.com/FigBug/Gin/tree/ca3e7f02c88a15516199dd2f16b7b20f6ebc936f as in slPlugins.

Thank you in advance.

**Comment by FigBug** [comment]
All updated
